export const QUERY_SENSORS = 'QUERY_SENSORS';
export const QUERY_SENSORS_OK = 'QUERY_SENSORS_OK';
export const QUERY_SENSORS_FAILED = 'QUERY_SENSORS_FAILED';

export const QUERY_CAMERAS = 'QUERY_CAMERAS';

export const QUERY_CAMERAS_OK = 'QUERY_CAMERAS_OK';
export const QUERY_CAMERAS_FAILED = 'QUERY_CAMERAS_OK';
